### ISSUE TITLE
[Epic] Integration Testing

### ISSUE THREAD

**Issue by frrist** [filecoin-project/sentinel-visor#246]
### Background
Visor needs integration testing to ensure it continues to behave as indented. Iteration tests should be simple for a developer to run on their development box as well as in CI. Visor has lenses that allow it to interact with different representations of blockchain date: `lotus`, `lotusrepo`, `carrepo`, and `sql` are the current lenses supported by visor. With the exception of the `sql` lens all of these can be can be derived from a CAR file. 

Visor can be tested via a CAR file by downloading one (e.g. [here](https://gateway.pinata.cloud/ipfs/QmVNq6nX7mhnwCkdFUaDDNFyv7t8jggUHXqaPSN8p46naL)) and running various workflows using it as a data source with the `carrepo` lens.

### Acceptance Criteria
- [ ] Integration tests are written with coverage for:
  - [ ] historical indexing
  - [ ] actor state changes
  - [ ] actor state extraction
  - [ ] message extraction
  - [ ] derived message extraction
  - [ ] gas output extraction
  - [ ] chain economics extraction
- [ ] A developer can run a single command to run integration tests on their local environment.
- [ ] Integration tests are run in CI.

**Comment by frrist** [comment]
This issue has rotted, closing.
